### ISSUE TITLE
2020 - OWASP Global Board Election Call for Questions

### ISSUE THREAD

**Issue by hblankenship** [OWASP-Foundation/Board-Election-Call-for-Questions#4]
Please post your questions as comments to this issue. For questions you like, you can 'upvote' them by clicking the 'thumbs up' icon. This call for questions will begin on **August 15th, 2020** and end on **August 31st, 2020**.

**Please submit only one question per comment** so that the individual questions may be upvoted.

**Comment by bkimminich** [comment]
How will you help active projects thrive and become (even) more recognized and used by the software industry?

**Comment by bkimminich** [comment]
How will you help OWASP to provide a (even) better user experience to our target audience via our websites and GitHub organization?

**Comment by thombrem** [comment]
How will you integrate Secure coding practices for use worldwide by newbie contributors? One method is to make a toolchain comprising static secure code analyzers.

**Comment by dune73** [comment]
Do you have previous experience running / sitting in the board of a large international non-profit? If yes, please describe the non-profit and your experience.

**Comment by 0-mm** [comment]
What do you think about OWASP membership? and what aspects do you think would need improving ?

**Comment by roberto8080** [comment]
Do you think we need more industry partnerships to improve the recognition and collaboration with the broader security community? If so, what kind of specific partnerships would be beneficial for us?

**Comment by varun1425** [comment]
How do you plan to utilise the evolving knowledge of OWASP members from their different organisations into newer initiatives of OWASP?

**Comment by rietta** [comment]
In your opinion, what does the future of application security look like with increasingly vendorless infrastructure from open source projects being used within enterprises and subject to downstream audit requirements?

**Comment by chefchristopher** [comment]
What is your plan for increasing women and minority participation in OWASP?

**Comment by didadida5555** [comment]
How will you enable outreach to developers as OWASP still is mainly a 'security people' place more than a 'developer' one?

**Comment by coderpatros** [comment]
What do you think is the biggest challenge the OWASP foundation faces in the short to medium term? And what do you think can be done about it?

**Comment by stevespringett** [comment]
What is the ideal method of creating policies for and about chapters, projects and their leaders? Compare the ideal to what's recently been done. Would you do anything different? If so, what?

**Comment by northdpole** [comment]
Do you have a plan for supporting digital outreach efforts and webinars until we can organise face to face events again?

**Comment by PBDataRecon** [comment]
As application security has been evolving at an exponential pace, so have the required skills to be an application security professional. Where do you see the profession in five years and how can OWASP support its members in this transformation?

**Comment by 0-mm** [comment]
What do you think about the tooling offered by OWASP.org and how would you improve any of these offerings ?

**Comment by sakhilouw** [comment]
What do you see as the most beneficial aspect of diversity and inclusion to OWASP and to your work?

**Comment by hblankenship** [comment]
Call for Questions is now closed.
