### ISSUE TITLE
Board Questions 

### ISSUE THREAD

**Issue by latfj** [OWASP-Foundation/Board-Election-Call-for-Questions#6]
Do you have experience serving on a board of Directors?
What type of fund raising experience do you have?
How do handle conflict resolution?
What type of leader are you?
Do you know the difference between operational and board responsibilities?

**Comment by bkimminich** [comment]
Please post as a comment on the existing issue #5 instead.

**Comment by hblankenship** [comment]
Questions closed on August 31 in the original Issue.
