### ISSUE TITLE
2022 - OWASP Global Board Election Call for Questions 

### ISSUE THREAD

**Issue by dawnaitken** [OWASP-Foundation/Board-Election-Call-for-Questions#7]
Please post your questions as comments to this issue. For questions you like, you can 'upvote' them by clicking the 'thumbs up' icon. This call for questions will begin on August 15th, 2022 and end on August 31st, 2022.

Please submit only one question per comment so that the individual questions may be upvoted.

**Comment by ae61195p** [comment]
How do you plan to engage prospective members & new-comers to OWASP in a post-covid world?

**Comment by tghosth** [comment]
How do you intend to extend outreach to developers and developer communities outside of the security ecosystem?

**Comment by istr** [comment]
How do you plan to become less dependent on the primary revenue stream of "Offline Conferences"?

**Comment by bkimminich** [comment]
Where do you see the biggest challenges for OWASP as a volunteer-driven organization in 2023+ and how do you intend to address them?

**Comment by kwwall** [comment]
Somewhat related to https://github.com/OWASP-Foundation/Board-Election-Call-for-Questions/issues/7#issuecomment-1216595417: What would you do to encourage OWASP to build more security tools, languages, and/or libraries for the developer community or help them assist developers by evaluating and recommending already existing FOSS libraries supporting security controls.

**Comment by tghosth** [comment]
What involvement have you had in the last 1-3 years as an OWASP project/chapter/conference leader which would give you an insight into the practical, day-to-day challenges which OWASP faces?

**Comment by tghosth** [comment]
What practical experience can you bring to the specific challenges a nonprofit organization like OWASP faces such as fundraising, staff support, operating model/by-laws, etc?

**Comment by pendo19** [comment]
How active do you intend on being? In the past there have been people doing the role for the title only without putting in the work.

**Comment by avidouglen** [comment]
How do you feel about compromising on your goals, in order to build consensus with others at the table that might disagree about those goals?

**Comment by evodefense** [comment]
Give an example of how you would lead the OWASP community to achieving its main goal of increasing security of software?

**Comment by evodefense** [comment]
Elaborate on how you would see yourself in this role. What your first day on the board would be like,end of your first month and the end of the year? What are you doing, reflecting, and setting goals?

**Comment by longwoodprof** [comment]
How can OWASP help address the problems of "everyone is hiring, but no one is hiring entry-level" and "How can I get experience when every job requires X years of experience?"

**Comment by longwoodprof** [comment]
Related:

How can OWASP better reach out to university students?

**Comment by VinodAnandan** [comment]
- What would you do to support the OWASP Projects and Chapters? 
- What do you think will help to increase the adoption of the OWASP Projects? 
- How will you help to improve the enterprise and government participation (membership and contribution to projects)?

**Comment by bkimminich** [comment]
> - What would you do to support the OWASP Projects and Chapters? 
> - What do you think will help to increase the adoption of the OWASP Projects? 
> - How will you help to improve the enterprise and government participation (membership and contribution to projects)?

_"Please submit only one question per comment so that the individual questions may be upvoted."_

**Comment by VinodAnandan** [comment]
What do you think will help to increase the adoption of the OWASP Projects?

**Comment by VinodAnandan** [comment]
How will you help to improve the enterprise and government participation (membership and contribution to projects)?

**Comment by curphey** [comment]
> Give an example of how you would lead the OWASP community to achieving its main goal of increasing security of software?

Can you clarify what you mean by increasing software security? Increasing adoption (if so by developers, general security people etc ?)

**Comment by curphey** [comment]
> Give an example of how you would lead the OWASP community to achieving its main goal of increasing security of software?

Can you clarify what you mean by increasing software security? Increasing adoption (if so by developers, general security people etc ?)

**Comment by evodefense** [comment]
> > Give an example of how you would lead the OWASP community to achieving its main goal of increasing security of software?
> 
> 
> 
> Can you clarify what you mean by increasing software security? Increasing adoption (if so by developers, general security people etc ?)

I was pulling this from OWASP website home page whois. My thought... Maybe an open ended question could offer a good candidate an opportunity to express his own new ideas or may be a bad candidate to fumble with the question about what owasp does. But I see your point more clarity in my question could provide a better answer! Still trying to brainstorm more ideas...

**Comment by hellodanielting** [comment]
Local laws increasingly require a local legal presence within a country (or the EEA) to operate and comply with local laws; how will you enable OWASP Chapters, Events, Projects and other activities outside the USA to continue operating in compliance with local laws (such as local Tax and Privacy laws) so that they won't need to shutdown? 

What actions can we expect to see from you within the first 3 months of your term to address this issue?

**Comment by hellodanielting** [comment]
How will you ensure that you're effectively representing the OWASP membership, its projects, and chapters? 
How will the community be able to measure that success?

**Comment by hellodanielting** [comment]
How will you enable OWASP, its projects, chapters, events, volunteers, staff, and members to better execute on its mission? 
What concrete actions/initiatives/programs will you drive during your time in office?

**Comment by hellodanielting** [comment]
With the growth of other community groups, such as OpenSSF, DevSecCon, and DefCon AppSec Village, GitHub/GitLab/Twitter, and the various local meetups, where do you see OWASP's Foundation place in the growing AppSec ecosystem?

**Comment by hellodanielting** [comment]
What do you believe are the biggest challenges the OWASP Foundation faces as an organisation in the next 1, and 5+ years respectively? What needs to urgently change/sustain/improve? How will you address them?

**Comment by hellodanielting** [comment]
What is your top outcome you'd like to accomplish in your term in office? How will the OWASP community be able to watch your progress?

**Comment by bhaskarvilles** [comment]
Why Is Joining OWASP Board Important to You? and to to the community?

**Comment by d00rma8** [comment]
What will be your significant milestones over the period of your tenure to make the OWASP community bigger and better?

**Comment by istr** [comment]
To be honest: I am shocked that we have 16 (!) participants on this ticket before closing.
As a question out of the official submission: Could you point out the ratio (voting OWASP members to 16)?
How do you plan to improve on that ratio?

**Comment by bkimminich** [comment]
> To be honest: I am shocked that we have 16 (!) participants on this ticket before closing.
> As a question out of the official submission: Could you point out the ratio (voting OWASP members to 16)?
> How do you plan to improve on that ratio?

You think 16 is bad? Check last year's ticket with questions from just 8 people... 😅

**Comment by longwoodprof** [comment]
How were the questions from this thread selected for the candidates?  It looked like none of them answered either of mine.  Were they overlooked or did I miss a step?

**Comment by bkimminich** [comment]
> How were the questions from this thread selected for the candidates?  It looked like none of them answered either of mine.  Were they overlooked or did I miss a step?

Questions are supposedly selected by # of "👍" given.
