### ISSUE TITLE
 OWASP 2023 Global Board Election Call for Questions

### ISSUE THREAD

**Issue by hblankenship** [OWASP-Foundation/Board-Election-Call-for-Questions#8]
Please post your questions as comments to this issue. For questions you like, you can 'upvote' them by clicking the 'thumbs up' icon. This call for questions will begin on August 15, 2023 and end on August 31, 2023.

Please submit only one question per comment so that the individual questions may be upvoted.

**Comment by Evtloglvl** [comment]
How do you envision the future of project who are mature enough to become a standard or in the same league as commercial software ?

**Comment by northdpole** [comment]
- What are your plans for foundation outreach in both government/policy  and industry ?
- What do you plan to do to increase funding for OWASP projects?
- what is the speed of an unladen swallow?

**Comment by yaneshtyagi** [comment]
How do you envision OWASP to become more reachable to individual developers and institutions?

**Comment by kingthorin** [comment]
Are you able to devote the equivalent to a second full time job to your OWASP duties? (Many project leaders do)

**Comment by kingthorin** [comment]
Do you believe all OWASP board discussions etc should happen in the open? (They do not currently seem to.)

**Comment by kingthorin** [comment]
What are you plans to have the board and staff be more involved in project marketing/cheerleading?
(Shouldn't the board and staff be the biggest marketers/cheerleaders of OWASP projects?)

[As context consider how few board/staff (even members) actually help in #amplify on slack. That's only one example.]
