### ISSUE TITLE
Shape the future of OWASP, how?

### ISSUE THREAD

**Issue by drwetter** [OWASP-Foundation/Board-Election-Call-for-Questions#9]
* How do you envision the future of OWASP?
* What's your stance with respect to the [open letter](https://owasp-change.github.io/)
* Any ideas to get any of points on track? If so: in a sustainable way?

Context: As you might know, we lost a flagship project (ZAP) to the Linux Foundation. One board member who founded OWASP and returned stepped down in 2023.  He ~ [felt also a need of change but didn't get the support needed](https://www.linkedin.com/pulse/yesterdays-owasp-board-directors-meeting-i-resigned-my-mark-curphey/).

To me answers from the candidates how to shape the future of OWASP are the ones which make me vote.

**Comment by psiinon** [comment]
FYI SKF (another flagship project) also moved to the Linux Foundation.
